<#
    SYSTEM INFO & DRIVER AUDIT - PHAT TAN PC
    Version: 2.0 (GUI Tabs + Export)
#>

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

# --- GUI SETUP ---
$Form = New-Object System.Windows.Forms.Form
$Form.Text = "MAY SOI PHAN CUNG - PHAT TAN PC"
$Form.Size = New-Object System.Drawing.Size(900, 600)
$Form.StartPosition = "CenterScreen"
$Form.BackColor = [System.Drawing.Color]::FromArgb(30, 30, 30)
$Form.ForeColor = "White"
$Form.FormBorderStyle = "FixedSingle"
$Form.MaximizeBox = $false

# --- TAB CONTROL ---
$TabControl = New-Object System.Windows.Forms.TabControl
$TabControl.Location = New-Object System.Drawing.Point(10, 10)
$TabControl.Size = New-Object System.Drawing.Size(865, 480)
$Form.Controls.Add($TabControl)

# Hàm tạo Tab
function Make-Tab ($Title) {
    $Page = New-Object System.Windows.Forms.TabPage
    $Page.Text = $Title
    $Page.BackColor = [System.Drawing.Color]::FromArgb(45, 45, 48)
    $Page.ForeColor = "Black" # Fix lỗi hiển thị text trên một số máy
    $TabControl.Controls.Add($Page)
    return $Page
}

# --- TAB 1: TỔNG QUAN (SYSTEM) ---
$TabSys = Make-Tab "Tong Quan He Thong"
$TxtSys = New-Object System.Windows.Forms.TextBox
$TxtSys.Multiline = $true; $TxtSys.ScrollBars = "Vertical"
$TxtSys.Size = New-Object System.Drawing.Size(840, 440); $TxtSys.Location = New-Object System.Drawing.Point(10, 10)
$TxtSys.BackColor = "Black"; $TxtSys.ForeColor = "Lime"; $TxtSys.Font = "Consolas, 10"
$TxtSys.ReadOnly = $true
$TabSys.Controls.Add($TxtSys)

# --- TAB 2: DRIVERS (GRID VIEW) ---
$TabDrv = Make-Tab "Chi Tiet Driver"
$GridDrv = New-Object System.Windows.Forms.DataGridView
$GridDrv.Size = New-Object System.Drawing.Size(840, 440); $GridDrv.Location = New-Object System.Drawing.Point(10, 10)
$GridDrv.BackgroundColor = "Black"; $GridDrv.ForeColor = "Black"
$GridDrv.AllowUserToAddRows = $false; $GridDrv.RowHeadersVisible = $false
$GridDrv.AutoSizeColumnsMode = "Fill"
$GridDrv.SelectionMode = "FullRowSelect"; $GridDrv.ReadOnly = $true
$TabDrv.Controls.Add($GridDrv)

# --- LOGIC LẤY THÔNG TIN (WMI/CIM) ---
function Get-FullSystemInfo {
    $TxtSys.Text = "Dang quet phan cung... Vui long doi..."
    $Form.Refresh()

    # 1. OS INFO
    $OS = Get-CimInstance Win32_OperatingSystem
    $CS = Get-CimInstance Win32_ComputerSystem
    $Bios = Get-CimInstance Win32_BIOS

    # 2. CPU & RAM
    $CPU = Get-CimInstance Win32_Processor
    $RAM_GB = [Math]::Round($CS.TotalPhysicalMemory / 1GB, 1)
    
    # 3. GPU (Lấy tất cả card)
    $GPUs = Get-CimInstance Win32_VideoController
    $GpuStr = ""
    foreach ($G in $GPUs) { $GpuStr += "  + $($G.Name) ($($G.DriverVersion))`r`n" }

    # 4. NETWORK (Lấy IP & MAC)
    $Nets = Get-CimInstance Win32_NetworkAdapterConfiguration | Where-Object {$_.IPEnabled -eq $true}
    $NetStr = ""
    foreach ($N in $Nets) { $NetStr += "  + $($N.Description)`r`n    IP: $($N.IPAddress[0]) | MAC: $($N.MACAddress)`r`n" }

    # 5. STORAGE
    $Disks = Get-Disk
    $DiskStr = ""
    foreach ($D in $Disks) { 
        $Type = if ($D.MediaType) { $D.MediaType } else { "Unspecified" }
        $DiskStr += "  + Disk $($D.Number): $($D.Model) - $([Math]::Round($D.Size/1GB)) GB ($Type) - $($D.PartitionStyle)`r`n" 
    }

    # FORMAT TEXT OUTPUT
    $Report = @"
======================================================
             BAO CAO CHI TIET HE THONG
             May: $($CS.Name) | User: $($env:USERNAME)
======================================================

[HE DIEU HANH]
  Ten:          $($OS.Caption)
  Phien ban:    $($OS.Version) (Build $($OS.BuildNumber))
  Kien truc:    $($OS.OSArchitecture)
  Ngay cai:     $($OS.InstallDate)
  Trang thai:   $(if($OS.SerialNumber){"Da kich hoat"}else{"Chua ro"})

[BO MACH CHU (MAINBOARD)]
  Hang:         $($CS.Manufacturer)
  Model:        $($CS.Model)
  BIOS Ver:     $($Bios.SMBIOSBIOSVersion) (Date: $($Bios.ReleaseDate))
  Serial:       $($Bios.SerialNumber)

[VI XU LY (CPU)]
  Ten:          $($CPU.Name)
  So nhan/luong:$($CPU.NumberOfCores) Cores / $($CPU.NumberOfLogicalProcessors) Threads
  Toc do:       $($CPU.MaxClockSpeed) MHz

[BO NHO TRONG (RAM)]
  Tong dung luong: $RAM GB

[DO HOA (GPU)]
$GpuStr
[LUU TRU (DISK)]
$DiskStr
[MANG (NETWORK)]
$NetStr
======================================================
Report generated by PHAT TAN PC TOOLKIT
"@
    $TxtSys.Text = $Report
}

function Get-DriverList {
    # Lấy danh sách Driver đang chạy (Signed)
    $Drivers = Get-WmiObject Win32_PnPSignedDriver | Where-Object { $_.DeviceName -ne $null } | Select-Object DeviceName, Manufacturer, DriverVersion, DriverDate, InfName

    $DT = New-Object System.Data.DataTable
    $DT.Columns.Add("Ten Thiet Bi"); $DT.Columns.Add("Hang SX"); $DT.Columns.Add("Phien Ban"); $DT.Columns.Add("Ngay"); $DT.Columns.Add("File INF")
    
    foreach ($D in $Drivers) {
        $R = $DT.NewRow()
        $R["Ten Thiet Bi"] = $D.DeviceName
        $R["Hang SX"] = $D.Manufacturer
        $R["Phien Ban"] = $D.DriverVersion
        # Fix format ngày
        try { $DateObj = [DateTime]::ParseExact($D.DriverDate.Substring(0,8), "yyyyMMdd", $null); $R["Ngay"] = $DateObj.ToString("yyyy-MM-dd") } catch { $R["Ngay"] = $D.DriverDate }
        $R["File INF"] = $D.InfName
        $DT.Rows.Add($R)
    }
    $GridDrv.DataSource = $DT
}

# --- BUTTONS ---
$BtnExportTXT = New-Object System.Windows.Forms.Button
$BtnExportTXT.Text = "XUAT REPORT (TXT)"
$BtnExportTXT.Location = "20,510"; $BtnExportTXT.Size = "180,40"; $BtnExportTXT.BackColor = "Cyan"; $BtnExportTXT.ForeColor = "Black"
$BtnExportTXT.Add_Click({
    $Path = "$env:USERPROFILE\Desktop\System_Info.txt"
    $TxtSys.Text | Out-File $Path
    [System.Windows.Forms.MessageBox]::Show("Da xuat file TXT ra Desktop!", "Thanh Cong")
})
$Form.Controls.Add($BtnExportTXT)

$BtnExportHTML = New-Object System.Windows.Forms.Button
$BtnExportHTML.Text = "XUAT DRIVER (HTML)"
$BtnExportHTML.Location = "220,510"; $BtnExportHTML.Size = "180,40"; $BtnExportHTML.BackColor = "Orange"; $BtnExportHTML.ForeColor = "Black"
$BtnExportHTML.Add_Click({
    $Path = "$env:USERPROFILE\Desktop\Driver_Report.html"
    $Header = "<style>table{border-collapse:collapse;width:100%} th,td{border:1px solid #ddd;padding:8px} th{background-color:#4CAF50;color:white}</style><h2>DRIVER REPORT - PHAT TAN PC</h2>"
    $Body = $GridDrv.DataSource | ConvertTo-Html -Fragment
    "$Header $Body" | Out-File $Path
    [System.Windows.Forms.MessageBox]::Show("Da xuat file HTML ra Desktop!", "Thanh Cong")
    Invoke-Item $Path
})
$Form.Controls.Add($BtnExportHTML)

# --- AUTO RUN ---
Get-FullSystemInfo
Get-DriverList

$Form.ShowDialog() | Out-Null
