Add-Type -AssemblyName System.Windows.Forms; Add-Type -AssemblyName System.Drawing
$SForm = New-Object System.Windows.Forms.Form; $SForm.Text = "SYSTEM HEALTH SCAN - PHAT TAN PC"; $SForm.Size = New-Object System.Drawing.Size(600, 400); $SForm.StartPosition = "CenterScreen"; $SForm.BackColor = "Black"; $SForm.ForeColor = "Lime"
$TxtLog = New-Object System.Windows.Forms.TextBox; $TxtLog.Multiline = $true; $TxtLog.ScrollBars = "Vertical"; $TxtLog.Location = New-Object System.Drawing.Point(10, 10); $TxtLog.Size = New-Object System.Drawing.Size(560, 280); $TxtLog.BackColor = [System.Drawing.Color]::FromArgb(20,20,20); $TxtLog.ForeColor = "White"; $TxtLog.Font = "Consolas, 9"; $SForm.Controls.Add($TxtLog)
function Log ($M) { $TxtLog.AppendText("[$([DateTime]::Now.ToString('HH:mm:ss'))] $M`r`n"); $SForm.Refresh() }
function Run-Cmd ($C) { Log "Running: $C"; $P = Start-Process "cmd" "/c $C" -NoNewWindow -PassThru -RedirectStandardOutput "$env:TEMP\scan.log"; while (!$P.HasExited) { $SForm.Refresh(); Start-Sleep -Milliseconds 500 }; Get-Content "$env:TEMP\scan.log" | ForEach { Log $_ }; Remove-Item "$env:TEMP\scan.log" -ErrorAction SilentlyContinue }
$B1 = New-Object System.Windows.Forms.Button; $B1.Text = "1. SFC SCAN"; $B1.Location = New-Object System.Drawing.Point(10, 310); $B1.Size = New-Object System.Drawing.Size(180, 40); $B1.BackColor = "Gray"; $B1.Add_Click({ $B1.Enabled=$false; Add-Log "=== START SFC ==="; Run-Cmd "sfc /scannow"; Add-Log "=== DONE ==="; $B1.Enabled=$true }); $SForm.Controls.Add($B1)
$B2 = New-Object System.Windows.Forms.Button; $B2.Text = "2. CHECK HEALTH"; $B2.Location = New-Object System.Drawing.Point(200, 310); $B2.Size = New-Object System.Drawing.Size(180, 40); $B2.BackColor = "Gray"; $B2.Add_Click({ $B2.Enabled=$false; Add-Log "=== START CHECK ==="; Run-Cmd "dism /online /cleanup-image /scanhealth"; Add-Log "=== DONE ==="; $B2.Enabled=$true }); $SForm.Controls.Add($B2)
$B3 = New-Object System.Windows.Forms.Button; $B3.Text = "3. RESTORE HEALTH"; $B3.Location = New-Object System.Drawing.Point(390, 310); $B3.Size = New-Object System.Drawing.Size(180, 40); $B3.BackColor = "Orange"; $B3.ForeColor = "Black"; $B3.Add_Click({ $B3.Enabled=$false; Add-Log "=== START RESTORE ==="; Run-Cmd "dism /online /cleanup-image /restorehealth"; Add-Log "=== DONE ==="; $B3.Enabled=$true }); $SForm.Controls.Add($B3)
$SForm.ShowDialog()
